name: Release Please

on:
  push:
    branches: [main]

permissions: {}
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release PR
        uses: chawyehsu/actions/release-pr@fffc3dd14b11dd2c19781ddce078b4c5d41811c7 # v1.0.0
        with:
          private-key: ${{ secrets.RELEASE_MAID_PRIVATE_KEY }}
