name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ github.ref_name }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Draft Release
        uses: chawyehsu/actions/create-release@32ef5b304a150e4251de26cea984db91d9dfcab1 # v1.1.0
