name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ github.ref_name }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Draft Release
        uses: chawyehsu/actions/create-release@fffc3dd14b11dd2c19781ddce078b4c5d41811c7 # v1.0.0
